# Environment options
width: 84
height: 84
ball: 0.5
ball_size: 1.0
snell: 0.5
snell_width: 40.0
snell_change: 0
snell_visible: "none"
#no_refraction:  # comment out to turn off
#uniform_speed:  # comment out to turn off
paddle_speed: 0.5
paddle_length: 10
paddle_angle: 70
state: "binary"
update_prob: 0.4

# Model and training options
episodes: 4000
learning_rate: 1e-4
network: dqn_pong_model
replay: 10000
#rankbased: # comment out to turn off
#priority: # comment out to turn off
#pretrain:  # comment out to turn off

# File control options
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
