# Environment options
width: 160
height: 160
ball: 3.0
ball_size: 2.0
snell: 2.0
snell_width: 40.0
snell_change: 0
snell_visible: "none"
#no_refraction:  # comment out to turn off
paddle_speed: 3.0
paddle_length: 45
paddle_angle: 45
state: "binary"

# Model and training options
episodes: 4000
learning_rate: 1e-4
update_prob: 0.2
network: dqn_pong_model
replay: 10000
#rankbased: # comment out to turn off
#priority: # comment out to turn off
#pretrain:  # comment out to turn off

# File control options
#resume:  # comment out to turn off
#checkpoint: dqn_pong_model
#history: history.p
